FinalProjectITI/Areas/Admin/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectITI.Data;
using FinalProjectITI.Models;
using FinalProjectITI.Services;

namespace FinalProjectITI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BlogController : Controller
    {
        private readonly IBaseService<Blog> blogservice;

        public BlogController(IBaseService<Blog> blogservice)
        {
            this.blogservice = blogservice;
        }

        // GET: Admin/Blog
        public async Task<IActionResult> Index()
        {
            

            return View(blogservice.GetAll());
        }

        // GET: Admin/Blog/Details/5
        public async Task<IActionResult> Details(int id)
        {
           

            if (id == null)
            {
                return NotFound();
            }

            return View(blogservice.GetByID(id));
        }

        // GET: Admin/Blog/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Admin/Blog/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Blog_ID,Blog_Title,Blog_Content,Blog_Date")] Blog blog)
        {
            
            if (!ModelState.IsValid)
                return View(blog);
            try
            {
                blogservice.Add(blog);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(blog);
            }
        }

        // GET: Admin/Blog/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
           
            if (id == null)
            {
                return NotFound();
            }
            var product = blogservice.GetByID(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.blog = blogservice.GetByID(id);
            return View(product);
        }

        // POST: Admin/Blog/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Blog_ID,Blog_Title,Blog_Content,Blog_Date")] Blog blog)
        {
           
            if (id != blog.Blog_ID)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    blogservice.Update(id, blog);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Blog_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["Category_ID"] = new SelectList(_context.Categories, "Category_ID", "Category_Name", product.Category_ID);

            return View(blog);

        }

        // GET: Admin/Blog/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var blog = blogservice.GetByID(id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Admin/Blog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            blogservice.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            var check = false;
            var item = blogservice.GetByID(id);
            if (item != null)
            {
                check = true;
            }
            return check;
        }
    }
}

FinalProjectITI/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectITI.Data;
using FinalProjectITI.Models;
using FinalProjectITI.Services;

namespace FinalProjectITI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IBaseService<Category> categoryservice;

        public CategoryController(IBaseService<Category> categoryservice)
        {
            this.categoryservice = categoryservice;
        }

        // GET: Admin/Category
        public async Task<IActionResult> Index()
        {
            ViewBag.categories_Names = categoryservice.GetAll();
            return View( categoryservice.GetAll());
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }


            return View(categoryservice.GetByID(id));
        }

        // GET: Admin/Category/Create
        public IActionResult Create()
        {
            ViewBag.categories_Names = categoryservice.GetAll();
            return View();
        }

        // POST: Admin/Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Category_ID,Category_Name,Category_Describtion")] Category category)
        {
            ViewBag.categories_Names = categoryservice.GetAll();
            
            if (!ModelState.IsValid)
                return View(category);
            try
            {
                categoryservice.Add(category);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(category);
            }
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = categoryservice.GetByID(id);
            if (category == null)
            {
                return NotFound();
            }
            ViewBag.categories_Names = categoryservice.GetByID(id);
            return View(category);
        }

        // POST: Admin/Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Category_ID,Category_Name,Category_Describtion")] Category category)
        {
            if (id != category.Category_ID)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    categoryservice.Update(id, category);
                    //await _context.SaveChangesAsync();
                    //return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Category_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction( nameof(Index));

            }
            return View(category);
        }

            // GET: Admin/Category/Delete/5
            public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = categoryservice.GetByID(id);
            if (product == null)
            {
                return NotFound();
            }

            // categoryservice.Delete(id);
            return View(product);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            categoryservice.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            var check = false;
            var item = categoryservice.GetByID(id);
            if (item != null)
            {
                check = true;
            }
            return check;
        }

        public async Task<IActionResult> CategorySearch(string name)
        {
            List<Category> categ = categoryservice.Search(name);
            return View(categ);
        }
    }
}

FinalProjectITI/Controllers/ProductController.cs
using FinalProjectITI.Data;
using FinalProjectITI.Models;
using FinalProjectITI.Services;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectITI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IBaseService<Product> baseService;

        public ProductController(IBaseService<Product> baseService)
        {
            this.baseService = baseService;
        }
        public IActionResult Index(int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 16;
            var items = baseService.GetAll().ToPagedList(pageNumber, pageSize);
            return View(items);
        }
        public IActionResult ProductDetails(int id)
        {
            Product product = baseService.GetByID(id);
            return View(product);
        }
    }
}

FinalProjectITI/Views/Shared/_AdminMenuPartial.cshtml
<li class="nav-item dropdown show">
    <a class="dropdown-toggle nav-link text-dark" href="#" data-toggle="dropdown">Admin</a>
    <div class="dropdown-menu">
        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" asp-area="Admin" asp-controller="Blog" asp-action="Index">Blog</a>
    </div>
</li>

FinalProjectITI/Views/Shared/_ViewCategories.cshtml
@using FinalProjectITI.Models

<!-- Banner -->
<section>
    <div class="sec-banner bg0 p-t-80 p-b-50">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
                    <!-- Block1 -->
                    <div class="block1 wrap-pic-w">
                        <img src="~/images/banner-01.jpg" alt="IMG-BANNER">

                        <a href="product.html" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
                            <div class="block1-txt-child1 flex-col-l">
                                <span class="block1-name ltext-102 trans-04 p-b-8">
                                    Women
                                </span>

                                <span class="block1-info stext-102 trans-04">
                                    Spring 2018
                                </span>
                            </div>

                            <div class="block1-txt-child2 p-b-4 trans-05">
                                <div class="block1-link stext-101 cl0 trans-09">
                                    Shop Now
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
                    <!-- Block1 -->
                    <div class="block1 wrap-pic-w">
                        <img src="~/images/banner-02.jpg" alt="IMG-BANNER">

                        <a href="product.html" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
                            <div class="block1-txt-child1 flex-col-l">
                                <span class="block1-name ltext-102 trans-04 p-b-8">
                                    Men
                                </span>

                                <span class="block1-info stext-102 trans-04">
                                    Spring 2018
                                </span>
                            </div>

                            <div class="block1-txt-child2 p-b-4 trans-05">
                                <div class="block1-link stext-101 cl0 trans-09">
                                    Shop Now
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
                    <!-- Block1 -->
                    <div class="block1 wrap-pic-w">
                        <img src="~/images/banner-03.jpg" alt="IMG-BANNER">

                        <a href="product.html" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
                            <div class="block1-txt-child1 flex-col-l">
                                <span class="block1-name ltext-102 trans-04 p-b-8">
                                    Accessories
                                </span>

                                <span class="block1-info stext-102 trans-04">
                                    New Trend
                                </span>
                            </div>

                            <div class="block1-txt-child2 p-b-4 trans-05">
                                <div class="block1-link stext-101 cl0 trans-09">
                                    Shop Now
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>